Revamp splunkf
BYU-CCDC/public-ccdc-resources pull request #17
Opened 2023-11-21 22:53 UTC by Benni371

- Revamped splunk indexer build script to be clearer and additional functionality
       - added a  line to configure receiving port during install
       - added a couple of lines that would build our searches in during install
- Revamped splunk forwarder script to have more functionality and clearness
       - broke file into multiple functions
       - attempted to add FIM but its complicated to setup and get working with splunk
       -  had to be hacky a little with the way I looped through adding indexes since some earlier bash versions dont like nested arrays
       - included ways to add new log sources to our indexes
       - general error checking
- Wrote out a SavedSearches.conf file
       - This file has our basic searches included and gives us the ability to import them during indexer install
       - more complicated searches can be typed out
- Modified windows splunk installer to reference correct indexes

2023-11-22 01:12 UTC, Aaron-M-Anderson requested changes
I added a couple request changes

2023-11-22 01:12 UTC, Aaron-M-Anderson commented on splunk_setup/build.sh
for `function check_user` I think that the CCDCUser2 does _not_ have privileged (sudo) rights, so that's not entirely correct I believe.

2023-11-22 01:12 UTC, Aaron-M-Anderson commented on splunk_setup/savedsearches.conf
I wouldn't know if there were errors here or not

2023-11-22 01:12 UTC, Aaron-M-Anderson commented on splunk_setup/splunkf.sh
When installing the forwarder, there is something here in the code, which I can't exactly find, that when we were testing on Thursday seemed to be trying to install something in `/root/<I_cant_remember>` because the person was running the script as root. This didn't work because the distro we were running didn't have a `/root` directory by default. I'm not sure what was doing that in this code, but I would look into that if you haven't yet.

2023-11-22 01:47 UTC, Benni371 commented on splunk_setup/splunkf.sh
im not sure what that problem may be but it probably has to do with root not having a "home" directory. I found that CCDCUser1 with sudo privileges is able to do all that is needed. So root isnt needed which is why I changed some of that wording. So that should fix the problem. I can do some testing though. What distro and version was it?

2023-11-22 01:50 UTC, Benni371 commented on splunk_setup/savedsearches.conf
I copied these from my own instances savedsearch.conf so they should be correct

2023-11-28 05:38 UTC, AnnaPrattt approved these changes
Changes look great, from what I can tell the code is effective.

2023-11-30 16:39 UTC, Aaron-M-Anderson approved these changes

2023-11-30 16:39 UTC, Aaron-M-Anderson approved these changes

2023-11-30 16:46 UTC, Aaron-M-Anderson approved these changes

2023-11-30 16:46 UTC, Aaron-M-Anderson approved these changes
Reviewed

2023-11-30 18:06 UTC, jgiboney approved these changes

2023-11-30 18:06 UTC, merged