Nice repo
BYU-CCDC/public-ccdc-resources pull request #4
Opened 2023-04-29 22:58 UTC by hulto

2023-04-29 23:00 UTC, alexcote1 commented
wow, this needs to be pulled now. the prior version was just nothing compared to this fork. merge our i start using the superior fork

2023-04-30 00:17 UTC, MikeSE314 requested changes
This change doesn't appear to be beneficial.

2023-04-30 00:17 UTC, MikeSE314 commented on splunk-forwarders.md
This seems like a bad change.

2023-04-30 00:17 UTC, MikeSE314 commented on splunk-forwarders.md
> +Not once. 😎
Unclear.

2023-04-30 00:17 UTC, MikeSE314 commented on splunk-forwarders.md
> +Nawww logs are bad.
Citation needed.

2023-04-30 05:51 UTC, kaisil commented
Good ideas very good

2023-05-17 23:17 UTC, closed without merging

2023-05-17 23:17 UTC, jgiboney commented
Red team fun!